name: Docker
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'fwcd/kotlin-language-server'
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: fwcd/kotlin-language-server
      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.output.tags }}
          labels: ${{ steps.meta.output.labels }}
